name: Go template project workflow

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build frontend
        run:  docker-compose -f docker-compose.yml build